### ISSUE TITLE
问题点罗列

### ISSUE THREAD

**Issue by lamberken** [carbonlake/forum#1]
一些对Carbon的想法，从功能设计上讲，值得研究，但是花费时间去看，总觉得不是很清晰。

### 问题点
- 写入数据时，采用锁的方式，性能不高
- 与现有的组件并没有很好的结合到一起，例如hive、presto
- 功能和特性都挺好，但是很多地方并没有注释，或者成片的代码冗余、以及大段的代码，很难理解
- 目前社区不是很活跃，代码又很难以定位，出现问题不能及时解决
- 新增IndexServer后，也不是很好用，有问题

**Comment by lz8086** [comment]
提到的2、4两点深有感触
与hive基本没法一起使用
没看到有啥社区，目前就加了个qq群，也基本属于潜水状态

**Comment by zzcclp** [comment]
@lz8086 可以加下我的微信：xm_zzc，我拉你进微信群。
