### ISSUE TITLE
datamap问题

### ISSUE THREAD

**Issue by xiaohui0318** [carbonlake/forum#6]
既然mv跟表的很多定义都是一样的，当dm1是从表t1里面衍生出来后，如果有跟t1进行join时，如果所有的字段都能够从dm1里面取出来的话，那直接用dm1与那张表进行join就可以了吧？现在还是从大表抽的数据进行join的。未来这块是怎么考虑的？有往这方面开发的进展吗？我看现在已经可以用datamap跟其他表做join操作了，感觉方向是对的，中间就差做一个选择了。还有datamap的字段名能指定就更好了，

**Comment by zzcclp** [comment]
datamap的字段名：
create datamap main_table_mv1 using 'mv' as select sum(id) as sum_id,name as myname  这样定义不行吗？

**Comment by xiaohui0318** [comment]
目前我使用的Preagg，这个不行，mv我没用，mv现在有问题。查询的时候读取的数据量不太对。

**Comment by zzcclp** [comment]
数据量不对？能具体描述下吗

**Comment by zzcclp** [comment]
2.0 旧的pre-agg要废弃了，会增强mv，所以有问题可以提出来，我们尽快fix

**Comment by jackylk** [comment]
MV的设计就是为了做带join的预汇聚场景，例如有两张表t1, t2
```
CREATE TABLE t1 (userId INT, date DATE, score DOUBLE) STORED AS CARBONDATA
CREATE TABLE t2 (userId INT, age INT, sex STRING) STORED AS CARBONDATA
```

例如有个查询Q1, 求按年龄统计分数的分布
```
SELECT avg(score), age 
FROM t1 JOIN t2 ON t1.userId = t2.userId 
GROUP BY t2.age
```

建立物化视图，做age和sex的预汇聚
```
CREATE DATAMAP mv1 USING ‘mv' AS
     SELECT avg(score), age, sex
     FROM t1 JOIN t2 ON t1.userId = t2.userId 
     GROUP BY t2.age, t2.sex
```

建立这个MV后，同样下发Q1，就会扫描mv1，在mv1基础上做age的汇聚，而不会重新去做join计算，响应会快很多。
又如下面这些带过滤的查询，都可以利用mv1基础上做二次计算得出。
```
SELECT avg(score), age 
FROM t1 JOIN t2 ON t1.userId = t2.userId 
GROUP BY t2.age 
WHERE t2.age =  12

SELECT avg(score), age, sex 
FROM t1 JOIN t2 ON t1.userId = t2.userId 
GROUP BY t2.age, sex
WHERE t2.age =  12
```

看看是否能解答你的问题？
